# Generated by Django 5.2.17 on 2026-08-05 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underwriting", "0003_populate_coverages"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="applicationcoverage",
            name="unique_coverage_per_application",
        ),
        migrations.RemoveField(
            model_name="applicationcoverage",
            name="legacy_coverage_code",
        ),
        migrations.AlterField(
            model_name="applicationcoverage",
            name="coverage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_coverages",
                to="underwriting.coverage",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationcoverage",
            constraint=models.UniqueConstraint(
                fields=("application", "coverage"),
                name="unique_coverage_per_application",
            ),
        ),
    ]
