# Generated by Django 5.2.17 on 2026-08-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "underwriting",
            "0004_remove_applicationcoverage_unique_coverage_per_application_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgramQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_key", models.CharField(max_length=100)),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Yes/No"),
                            ("select", "Select"),
                            ("multi_select", "Multi Select"),
                            ("date", "Date"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("help_text", models.TextField(blank=True)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distribution_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="underwriting.distributionpartner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="underwriting.program",
                    ),
                ),
                (
                    "rating_engine_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_versions",
                        to="underwriting.ratingengineversion",
                    ),
                ),
            ],
            options={
                "ordering": ["program", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ProgramRatingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating_engine_key", models.CharField(max_length=100)),
                (
                    "value_source",
                    models.CharField(
                        choices=[
                            ("direct_answer", "Direct Answer"),
                            ("static_value", "Static Value"),
                        ],
                        max_length=30,
                    ),
                ),
                ("static_value", models.JSONField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "source_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rating_configs",
                        to="underwriting.programquestion",
                    ),
                ),
                (
                    "program_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_configs",
                        to="underwriting.programversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="programquestion",
            name="program_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="underwriting.programversion",
            ),
        ),
        migrations.CreateModel(
            name="ProgramDiscountConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("rating_engine_key", models.CharField(blank=True, max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        max_length=30,
                    ),
                ),
                (
                    "default_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "minimum_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "maximum_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "program_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_configs",
                        to="underwriting.programversion",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProgramCoverageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "default_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "default_deductible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "minimum_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "maximum_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "coverage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_configs",
                        to="underwriting.coverage",
                    ),
                ),
                (
                    "program_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_configs",
                        to="underwriting.programversion",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("distribution_partner", "code"),
                name="unique_program_code_per_partner",
            ),
        ),
        migrations.AddConstraint(
            model_name="programversion",
            constraint=models.UniqueConstraint(
                fields=("program", "version"), name="unique_version_per_program"
            ),
        ),
        migrations.AddConstraint(
            model_name="programratingconfig",
            constraint=models.UniqueConstraint(
                fields=("program_version", "rating_engine_key"),
                name="unique_rating_key_per_program_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="programquestion",
            constraint=models.UniqueConstraint(
                fields=("program_version", "question_key"),
                name="unique_question_key_per_program_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="programdiscountconfig",
            constraint=models.UniqueConstraint(
                fields=("program_version", "code"),
                name="unique_discount_code_per_program_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="programcoverageconfig",
            constraint=models.UniqueConstraint(
                fields=("program_version", "coverage"),
                name="unique_coverage_per_program_version",
            ),
        ),
    ]
