# Generated by Django 5.2.17 on 2026-08-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underwriting", "0005_distributionpartner_programquestion_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="program_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="underwriting.programversion",
            ),
        ),
    ]
