# Generated by Django 5.2.17 on 2026-08-05 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underwriting", "0006_application_program_version"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="applicationanswer",
            name="unique_answer_per_application_question",
        ),
        migrations.AddField(
            model_name="applicationanswer",
            name="program_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="underwriting.programquestion",
            ),
        ),
        migrations.AlterField(
            model_name="applicationanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="underwriting.applicationquestion",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("question__isnull", False), ("program_question__isnull", True)
                    ),
                    models.Q(
                        ("question__isnull", True), ("program_question__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="answer_has_exactly_one_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("question__isnull", False)),
                fields=("application", "question"),
                name="unique_standard_answer_per_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("program_question__isnull", False)),
                fields=("application", "program_question"),
                name="unique_program_answer_per_question",
            ),
        ),
    ]
