# Generated by Django 5.2.17 on 2026-08-05 22:58
from django.db import migrations


def migrate_partner_answers(apps, schema_editor):
    ApplicationAnswer = apps.get_model(
        "underwriting",
        "ApplicationAnswer",
    )

    ProgramQuestion = apps.get_model(
        "underwriting",
        "ProgramQuestion",
    )

    answers = ApplicationAnswer.objects.filter(
        application__program_version__isnull=False,
        question__isnull=False,
        question__is_pricing_modifier=False,
        program_question__isnull=True,
    ).select_related(
        "application",
        "question",
    )

    for answer in answers:
        program_question = ProgramQuestion.objects.get(
            program_version_id=(
                answer.application.program_version_id
            ),
            question_key=(
                answer.question.rating_engine_question_key
            ),
        )

        ApplicationAnswer.objects.filter(
            pk=answer.pk,
        ).update(
            question_id=None,
            program_question_id=program_question.id,
        )


def reverse_partner_answers(apps, schema_editor):
    ApplicationAnswer = apps.get_model(
        "underwriting",
        "ApplicationAnswer",
    )

    ApplicationQuestion = apps.get_model(
        "underwriting",
        "ApplicationQuestion",
    )

    answers = ApplicationAnswer.objects.filter(
        application__program_version__isnull=False,
        program_question__isnull=False,
        question__isnull=True,
    ).select_related(
        "application",
        "program_question",
    )

    for answer in answers:
        application_question = ApplicationQuestion.objects.get(
            rating_engine_version_id=(
                answer.application.rating_engine_version_id
            ),
            rating_engine_question_key=(
                answer.program_question.question_key
            ),
        )

        ApplicationAnswer.objects.filter(
            pk=answer.pk,
        ).update(
            question_id=application_question.id,
            program_question_id=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "underwriting",
            "0007_remove_applicationanswer_unique_answer_per_application_question_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            migrate_partner_answers,
            reverse_partner_answers,
        ),
    ]