# Generated by Django 5.2.17 on 2026-08-05 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underwriting", "0008_migrate_partner_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=4, max_digits=8)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="underwriting.application",
                    ),
                ),
                (
                    "discount_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="application_discounts",
                        to="underwriting.programdiscountconfig",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "discount_config"),
                        name="unique_discount_per_application",
                    )
                ],
            },
        ),
    ]
